import os
import asyncio
import threading
from google import genai
from google.genai import types
import config
import api
from session import TripContext
from ui.theme import console
from rich.live import Live
from rich.markdown import Markdown
from rich.panel import Panel

SYSTEM_PROMPT = """
You are a highly capable AI Travel Guide assistant. You help travelers plan itineraries, budget, check visa rules, find flights, translate phrases, and suggest hotels.

Guidelines:
1. Provide styled responses using Rich formatting. Use markdown features like bold, italics, list items, tables, and blockquotes where appropriate.
2. Keep your tone enthusiastic, helpful, and concise.
3. Keep emoji usage minimal and elegant. Do not overuse them.
4. When answering budget, flight, or visa queries, try to be specific but add disclaimer notes when estimates are used.
5. You have tools to check live weather, convert currencies, fetch POIs, and plan itineraries. Always use these tools when a user asks about them.
6. Pay attention to the user's active trip context (destination, days, budget, currency) which is supplied dynamically. Use it to tailor your planning and chat answers.
"""

# Active session context references, set during interactive chat execution
_active_context = None
_active_agent = None

def run_async_coro(coro):
    """Runs an async coroutine in a separate thread with a new event loop, avoiding loop conflicts."""
    result = []
    error = []
    
    def worker():
        try:
            res = asyncio.run(coro)
            result.append(res)
        except Exception as e:
            error.append(e)
            
    t = threading.Thread(target=worker)
    t.start()
    t.join()
    
    if error:
        raise error[0]
    return result[0] if result else None

# --- Agent Tools ---

def check_weather(city: str) -> str:
    """
    Fetches and displays the live weather forecast table for the specified city.
    
    Args:
        city: The name of the city (e.g., "Paris", "Jaipur").
        
    Returns:
        A status message indicating success or failure.
    """
    from commands.weather import handle_weather
    try:
        run_async_coro(handle_weather([city], _active_context, _active_agent))
        return f"Successfully displayed live weather forecast for {city} directly in the console."
    except Exception as e:
        return f"Failed to display weather: {e}"

def plan_trip(destination: str, days: int) -> str:
    """
    Updates the active trip context with destination and days. Use this whenever the user wants 
    to plan a trip. Note: The actual day-by-day itinerary details must still be generated by you 
    in your final response.
    
    Args:
        destination: The target destination city/country (e.g., "Jaipur").
        days: The duration of the trip in days (e.g., 3).
        
    Returns:
        A message instructing you to write the itinerary.
    """
    try:
        if _active_context:
            _active_context.destination = destination
            _active_context.days = days
        return f"Updated trip context destination to {destination} and days to {days}. Now, please write the detailed day-by-day itinerary for {destination} in your final response."
    except Exception as e:
        return f"Failed to set plan context: {e}"

def estimate_flights(origin: str, destination: str, date: str) -> str:
    """
    Sets up a request for flight routes and cost estimates. Note: You must estimate and write the 
    carrier routes, travel times, and cost ranges in your final response.
    
    Args:
        origin: The departure city (e.g., "Delhi").
        destination: The arrival city (e.g., "London").
        date: The travel date (e.g., "2026-09-01").
        
    Returns:
        A prompt instructing you to estimate flights.
    """
    try:
        return f"Please list flight routes, airlines, and estimated cost ranges from {origin} to {destination} on {date} in your final response."
    except Exception as e:
        return f"Failed to set flights: {e}"

def suggest_hotels_and_pois(city: str) -> str:
    """
    Fetches and displays live local tourist attractions and points of interest (POIs) for a city.
    Note: You must still recommend hotels (budget, mid-range, luxury) in your final response.
    
    Args:
        city: The name of the city (e.g., "Jaipur", "Tokyo").
        
    Returns:
        A message instructing you to recommend hotels.
    """
    try:
        places = run_async_coro(api.get_places_pois(city))
        if places:
            from rich.table import Table
            table = Table(title=f"[travel.teal]Local Attractions in {city.title()}[/]", border_style="travel.sand")
            table.add_column("Name", style="travel.gold")
            table.add_column("Category", style="travel.teal")
            table.add_column("Description", style="travel.text")
            for p in places:
                table.add_row(p["name"], p["category"], p["description"])
            console.print(table)
            console.print()
            return f"Successfully displayed live local attractions for {city} to the console. Recommend hotels in {city} in your final response."
        else:
            return f"Could not find live attractions for {city}. Please recommend tourist places and hotels in {city} in your final response based on your own knowledge."
    except Exception as e:
        return f"Failed to get attractions: {e}"

def estimate_budget(destination: str, days: int) -> str:
    """
    Sets up a request for budget estimations. Note: You must estimate and write a structured 
    budget breakdown in your final response.
    
    Args:
        destination: The target destination (e.g., "Jaipur").
        days: The duration of the trip in days.
        
    Returns:
        A message instructing you to estimate the budget.
    """
    try:
        if _active_context:
            _active_context.destination = destination
            _active_context.days = days
        currency = _active_context.currency if _active_context else "INR"
        return f"Please write a detailed travel budget breakdown for visiting {destination} for {days} days in {currency} in your final response."
    except Exception as e:
        return f"Failed to set budget context: {e}"

def get_currency_conversion(from_currency: str, to_currency: str) -> str:
    """
    Fetches the current exchange rate between two currencies.
    
    Args:
        from_currency: The 3-letter source currency code (e.g., "USD").
        to_currency: The 3-letter target currency code (e.g., "INR").
        
    Returns:
        The exchange rate statement.
    """
    try:
        rate = asyncio.run(api.get_exchange_rate(from_currency, to_currency))
        if not rate:
            return f"Could not retrieve exchange rate from {from_currency} to {to_currency}."
        return f"1 {from_currency.upper()} = {rate:.4f} {to_currency.upper()}"
    except Exception as e:
        return f"Error retrieving exchange rate: {str(e)}"

# --- Agent Class ---

class TravelAgent:
    def __init__(self):
        self.model_name = os.getenv("GEMINI_MODEL", "gemma-4-31b-it")
        self.client = None
        self.chat = None
        self.is_initialized = False

    def initialize(self) -> bool:
        if not config.has_gemini_key():
            return False
        try:
            self.client = genai.Client(api_key=config.GEMINI_API_KEY)
            self.chat = self.client.chats.create(
                model=self.model_name,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_PROMPT,
                    tools=[
                        check_weather,
                        plan_trip,
                        estimate_flights,
                        suggest_hotels_and_pois,
                        estimate_budget,
                        get_currency_conversion
                    ],
                    automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True)
                )
            )
            self.is_initialized = True
            return True
        except Exception as e:
            console.print(f"[travel.error]Failed to initialize Gemini Client: {e}[/]")
            return False

    def load_history(self, chat_history: list) -> bool:
        """Loads and restores conversational history into the Gemini chat session."""
        if not self.is_initialized:
            if not self.initialize():
                return False
        try:
            history = []
            for h in chat_history:
                parts = []
                for p in h.get("parts", []):
                    parts.append(types.Part.from_text(text=p))
                history.append(types.Content(
                    role=h["role"],
                    parts=parts
                ))
            self.chat = self.client.chats.create(
                model=self.model_name,
                history=history,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_PROMPT,
                    tools=[
                        check_weather,
                        plan_trip,
                        estimate_flights,
                        suggest_hotels_and_pois,
                        estimate_budget,
                        get_currency_conversion
                    ],
                    automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True)
                )
            )
            return True
        except Exception as e:
            console.print(f"[travel.error]Failed to restore chat history: {e}[/]")
            return False

    def send_message_stream(self, message: str, context: TripContext):
        """Sends a message to the agent and streams the response to the console."""
        if not self.is_initialized:
            if not self.initialize():
                yield "[travel.error]Gemini client not initialized. Please set GEMINI_API_KEY.[/]"
                return

        context_str = ""
        if context.destination:
            context_str = (
                f"[Current Context - Destination: {context.destination}, "
                f"Days: {context.days or 'Flexible'}, Budget: {context.budget or 'Flexible'} {context.currency}]\n"
            )
        
        if isinstance(message, str):
            current_input = f"{context_str}User query: {message}"
        else:
            current_input = message

        tool_map = {
            "check_weather": check_weather,
            "plan_trip": plan_trip,
            "estimate_flights": estimate_flights,
            "suggest_hotels_and_pois": suggest_hotels_and_pois,
            "estimate_budget": estimate_budget,
            "get_currency_conversion": get_currency_conversion
        }

        while True:
            # Retry mechanism for transient errors (500, 503, 429)
            max_retries = 3
            delay = 2.0
            response_stream = None
            last_err = None
            
            for attempt in range(max_retries):
                try:
                    response_stream = self.chat.send_message_stream(current_input)
                    break
                except Exception as e:
                    last_err = e
                    err_str = str(e)
                    is_transient = any(code in err_str for code in ["500", "503", "429", "UNAVAILABLE", "INTERNAL", "RESOURCE_EXHAUSTED"])
                    if is_transient and attempt < max_retries - 1:
                        import time
                        time.sleep(delay)
                        delay *= 2
                        continue
                    else:
                        break
            
            if response_stream is None:
                yield f"[travel.error]Error during LLM response: {str(last_err)}[/]"
                return
                
            function_calls = []
            
            try:
                for chunk in response_stream:
                    if chunk.candidates and chunk.candidates[0].content:
                        for p in chunk.candidates[0].content.parts:
                            if p.function_call:
                                function_calls.append(p.function_call)
                            elif p.text is not None and not getattr(p, "thought", False):
                                yield p.text
            except Exception as e:
                yield f"[travel.error]Error during LLM response: {str(e)}[/]"
                return
                
            if not function_calls:
                break
                
            # Execute function calls and send responses back
            tool_responses = []
            for fc in function_calls:
                fn = tool_map.get(fc.name)
                if fn:
                    try:
                        args = fc.args
                        kwargs = {}
                        if args:
                            kwargs = dict(args)
                        result = fn(**kwargs)
                    except Exception as e:
                        result = f"Error executing tool {fc.name}: {e}"
                        
                    tool_responses.append(types.Part(
                        function_response=types.FunctionResponse(
                            name=fc.name,
                            response={"result": result},
                            id=fc.id
                        )
                    ))
                else:
                    tool_responses.append(types.Part(
                        function_response=types.FunctionResponse(
                            name=fc.name,
                            response={"result": f"Tool {fc.name} not found"},
                            id=fc.id
                        )
                    ))
            
            current_input = tool_responses

def ask_agent_interactive(agent: TravelAgent, prompt: str, context: TripContext):
    """Asks the agent a question and displays the response in real-time using Live."""
    global _active_context, _active_agent
    _active_context = context
    _active_agent = agent
    
    try:
        with console.status("[travel.teal]Thinking...[/]", spinner="dots") as status:
            stream = agent.send_message_stream(prompt, context)
            try:
                first_chunk = next(stream)
                full_text = first_chunk
            except StopIteration:
                return
                
        panel_content = Markdown(full_text)
        panel = Panel(panel_content, border_style="travel.teal", title="[travel.teal]🌍 Travel Guide[/]")
        
        with Live(panel, console=console, refresh_per_second=10) as live:
            for chunk in stream:
                full_text += chunk
                panel.renderable = Markdown(full_text)
                live.update(panel)
                
        context.chat_history.append({"role": "user", "parts": [prompt]})
        context.chat_history.append({"role": "model", "parts": [full_text]})
    finally:
        _active_context = None
        _active_agent = None
